services:
  - type: web
    name: jobbot-pro
    env: python
    buildCommand: poetry install
    startCommand: poetry run python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
